#!/bin/bash

cd ..
mvn clean package
mvn deploy:deploy-file -Dfile=$(echo target/oraman-*-dist.tgz) -DrepositoryId=touch-releases \
        -Durl=http://nexus.touchtec.com.br/content/repositories/releases \
        -DpomFile=pom.xml -Dpackaging=tgz

