#!/bin/bash

set -euo pipefail

sysprops="-Doraman.home=$(readlink -f ../target)"
sysprops+=" -Dspring.config.additional-location=$(readlink -f dev-config.yml)"
sysprops+=" -Dspring.profiles.include=foreground"

cd ..
mvn spring-boot:run -Dspring-boot.run.jvmArguments="$sysprops"

